### ISSUE TITLE
Wrong update query is being sent

### ISSUE THREAD

**Issue by GrabowskiKamil112** [axelotecom/issues#2] opened 2023-03-20 11:57 UTC
Cannot update items

fe request:
![image](https://user-images.githubusercontent.com/84017437/226330563-20530489-db32-44c5-9b66-b492d63301bd.png)

on the be:
![image](https://user-images.githubusercontent.com/84017437/226331874-61d2413b-6a3b-47ef-8e24-c0ab0c48062f.png)

queries:
![image](https://user-images.githubusercontent.com/84017437/226332522-debd1538-38cf-4b48-b505-06e102e9ea75.png)

table items:
![image](https://user-images.githubusercontent.com/84017437/226332897-e952749a-c67c-45a2-8ccd-1c8a32aab67a.png)

![image](https://user-images.githubusercontent.com/84017437/226428490-4b92a7b1-7858-4d66-91a7-78ff5155571f.png)

![image](https://user-images.githubusercontent.com/84017437/226428628-f65be464-1b72-40e6-8e87-5d8803909aac.png)
![image](https://user-images.githubusercontent.com/84017437/226428691-bf78e860-6bd1-4a2c-8316-2d64c3d93e32.png)

`export const updateItem = (invoiceContent: Invoice, invoiceId: string, markAsPaid = false): AppThunk =>
    async (dispatch, getState) => {
        dispatch({ type: ActionType.UPDATE_INVOICE_REQUEST })
        try {
        
            if(markAsPaid){
                const query = repository.get('markAsPaid');
                await axelote.void(query, {invoice_id: parseInt(invoiceId)});
                dispatch({ type: ActionType.UPDATE_INVOICE_SUCCESS, payload: { data } });
                return;
            }

            const invoiceData = structuredClone(invoiceContent);
            const invoiceItems: ItemsListEntity[] = mapDataToSend(invoiceData);

            const invoiceQuery = repository.get('updateInvoice', invoiceData);
            
            //let tx: AxeloteTransaction = axelote.transaction();
            
            await axelote.void(invoiceQuery, {
                ...invoiceData,
                ...{invoice_id: Number(invoiceId)}
            });
            
            invoiceItems.forEach(async (item, index) => {
                const itemId = Number(item.itemId)
                delete item.itemId;

                const invoiceItemsQuery = repository.get('updateInvoiceItems', item);
                await axelote.void(invoiceItemsQuery, {
                    ...item,
                    ...{item_id: itemId}
                });

                //await tx.commit();
            })
            

        } catch (err) {
            console.log('error:' + err)
            dispatch({ type: ActionType.UPDATE_INVOICE_FAILURE })
        }
    }`

`export const repository: AxeloteRepository = new AxeloteRepository();

repository.set('updateInvoice', (params: Record<string, any>) => {

    const qb: AxeloteQueryBuilder = AxeloteQueryBuilder.query('@sql update invoices set');

    for (const [index, [key, _value]] of Object.entries(Object.entries(params))) {
        
        if(Number(index) == Object.entries(params).length - 1){

            switch (key) {
                case 'payment_term': qb.append('@sql payment_term = :payment_term '); break;
                case 'description': qb.append('@sql description = :description '); break;
                case 'invoice_date': qb.append('@sql invoice_date = :invoice_date '); break;
                case 'address_from': qb.append('@sql address_from = :address_from '); break;
                case 'address_to': qb.append('@sql address_to = :address_to '); break;
                case 'type': qb.append('@sql type = :type '); break;
            }

        }else{

            switch (key) {
                case 'payment_term': qb.append('@sql payment_term = :payment_term, '); break;
                case 'description': qb.append('@sql description = :description, '); break;
                case 'invoice_date': qb.append('@sql invoice_date = :invoice_date, '); break;
                case 'address_from': qb.append('@sql address_from = :address_from, '); break;
                case 'address_to': qb.append('@sql address_to = :address_to, '); break;
                case 'type': qb.append('@sql type = :type, '); break;
            }

        }
       
    }

    qb.append('@sql where invoice_id = :invoice_id');

    return qb.build(); 
});

repository.set('updateInvoiceItems', (params: Record<string, any>) => {

    const qb: AxeloteQueryBuilder = AxeloteQueryBuilder.query('@sql update items set');

    for (const [index, [key, _value]] of Object.entries(Object.entries(params))) {
        
        if(Number(index) == Object.entries(params).length - 1){

            switch (key) {
                case 'name': qb.append('@sql name = :name '); break;
                case 'price': qb.append('@sql price = :price '); break;
                case 'quantity': qb.append('@sql quantity = :quantity '); break;
            }

        }else{

            switch (key) {
                case 'name': qb.append('@sql name = :name, '); break;
                case 'price': qb.append('@sql price = :price, '); break;
                case 'quantity': qb.append('@sql quantity = :quantity, '); break;
            }

        } 
       
    }

    qb.append('@sql where item_id = :item_id');

    return qb.build(); 
});`

**Comment by axelotecom** [comment] 2023-03-20 18:06
Please add code snippets if possible, debug logs from CLI. Also please confirm you use transaction because request payload doesnt indicate that

**Comment by GrabowskiKamil112** [comment] 2023-03-20 18:13
`
PS D:\Praca\invoiceApp\InvoiceApp-Frontend> npm run dev-axelote

> app@1.0.0 dev-axelote D:\Praca\invoiceApp\InvoiceApp-Frontend
> axelote hash -f src/**/*.{tsx,ts} --noWrite --debug

Axelote: Found 52 files to be processed
Axelote debug: di.getExecutor().cliParams {
  files: [
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\custom.d.ts',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\index.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\context\\pageContext.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\store\\index.ts',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\stories\\Button.stories.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\stories\\InvoiceController.stories.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\templates\\InvoiceShortTemplate.tsx',   
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\templates\\LoginRegisterTemplate.tsx',  
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\templates\\mainTemplate.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\templates\\ModalTempalate.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\templates\\NavigationTemplate.tsx',     
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\Types\\Invoice.ts',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\theme\\globalStyle.ts',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\theme\\theme.ts',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\utils\\Delayed.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\utils\\hooks.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\utils\\utils.ts',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\utils\\validation.ts',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\views\\App.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\views\\Home.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\views\\InvoiceDetails.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\views\\LoginRegister.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\Button.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\DropdownSelect.tsx', 
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\Errors.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\FormInput.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\Header.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\Icon.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\Input.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\Logo.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\Paragraph.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\Status.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\ThemeSwitcher.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Molecules\\AsideController.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Molecules\\ConfirmDeleteModal.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Molecules\\DetailsController.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Molecules\\FormItem.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Molecules\\InvoiceShort.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Molecules\\ItemsList.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Molecules\\UserCreatedModal.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Organisms\\InvoiceControllerBar.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Organisms\\Sidebar.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\store\\actions\\axeloteRepository.ts',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\store\\actions\\index.ts',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\store\\hooks\\hooks.ts',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\store\\reducers\\rootReducer.ts',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\FilterBy\\FilterBy-styling.ts',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\FilterBy\\FilterBy.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Molecules\\DetailsBody\\DetailsBody-styling.ts',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Molecules\\DetailsBody\\DetailsBody.tsx',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Organisms\\InvoiceForm\\InvoiceForm-styling.ts',
    'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Organisms\\InvoiceForm\\InvoiceForm.tsx'
  ]
}
Axelote debug: Time: 0ms 
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(28) {
  '@sql select invoice_id, address_to, type, payment_term from invoices where user_id = :user_id',
  "@sql UPDATE invoices set type = 'paid' where invoice_id = :invoice_id",
  '@sql select * from invoices where invoice_id = :invoice_id',
  '@sql DELETE FROM invoices WHERE invoice_id = :invoice_id',
  '@sql select * from items where invoice_id = :invoice_id',
  '@sql where invoice_id = :invoice_id',
  '@sql payment_term = :payment_term,',
  '@sql invoice_date = :invoice_date,',
  '@sql address_from = :address_from,',
  '@sql payment_term = :payment_term',
  '@sql invoice_date = :invoice_date',
  '@sql address_from = :address_from',
  '@sql description = :description,',
  '@sql description = :description',
  '@sql address_to = :address_to,',
  '@sql address_to = :address_to',
  '@sql where item_id = :item_id',
  '@sql quantity = :quantity,',
  '@sql quantity = :quantity',
  '@sql update invoices set',
  '@sql update items set',
  '@sql and type = :type',
  '@sql price = :price,',
  '@sql price = :price',
  '@sql type = :type,',
  '@sql name = :name,',
  '@sql type = :type',
  '@sql name = :name'
}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: Time: 0ms
Axelote debug: Matches:  Set(0) {}
Axelote debug: resolved queries from files Map(52) {
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\custom.d.ts' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\index.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\context\\pageContext.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\store\\index.ts' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\stories\\Button.stories.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\stories\\InvoiceController.stories.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\templates\\InvoiceShortTemplate.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\templates\\LoginRegisterTemplate.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\templates\\mainTemplate.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\templates\\ModalTempalate.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\templates\\NavigationTemplate.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\Types\\Invoice.ts' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\theme\\globalStyle.ts' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\theme\\theme.ts' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\utils\\Delayed.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\utils\\hooks.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\utils\\utils.ts' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\utils\\validation.ts' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\views\\App.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\views\\Home.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\views\\InvoiceDetails.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\views\\LoginRegister.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\Button.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\DropdownSelect.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\Errors.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\FormInput.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\Header.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\Icon.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\Input.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\Logo.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\Paragraph.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\Status.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\ThemeSwitcher.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Molecules\\AsideController.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Molecules\\ConfirmDeleteModal.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Molecules\\DetailsController.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Molecules\\FormItem.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Molecules\\InvoiceShort.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Molecules\\ItemsList.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Molecules\\UserCreatedModal.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Organisms\\InvoiceControllerBar.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Organisms\\Sidebar.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\store\\actions\\axeloteRepository.ts' => Set(28) {
    '@sql select invoice_id, address_to, type, payment_term from invoices where user_id = :user_id',
    "@sql UPDATE invoices set type = 'paid' where invoice_id = :invoice_id",
    '@sql select * from invoices where invoice_id = :invoice_id',
    '@sql DELETE FROM invoices WHERE invoice_id = :invoice_id',
    '@sql select * from items where invoice_id = :invoice_id',
    '@sql where invoice_id = :invoice_id',
    '@sql payment_term = :payment_term,',
    '@sql invoice_date = :invoice_date,',
    '@sql address_from = :address_from,',
    '@sql payment_term = :payment_term',
    '@sql invoice_date = :invoice_date',
    '@sql address_from = :address_from',
    '@sql description = :description,',
    '@sql description = :description',
    '@sql address_to = :address_to,',
    '@sql address_to = :address_to',
    '@sql where item_id = :item_id',
    '@sql quantity = :quantity,',
    '@sql quantity = :quantity',
    '@sql update invoices set',
    '@sql update items set',
    '@sql and type = :type',
    '@sql price = :price,',
    '@sql price = :price',
    '@sql type = :type,',
    '@sql name = :name,',
    '@sql type = :type',
    '@sql name = :name'
  },
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\store\\actions\\index.ts' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\store\\hooks\\hooks.ts' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\store\\reducers\\rootReducer.ts' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\FilterBy\\FilterBy-styling.ts' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Atoms\\FilterBy\\FilterBy.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Molecules\\DetailsBody\\DetailsBody-styling.ts' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Molecules\\DetailsBody\\DetailsBody.tsx' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Organisms\\InvoiceForm\\InvoiceForm-styling.ts' => Set(0) {},
  'D:\\Praca\\invoiceApp\\InvoiceApp-Frontend\\src\\components\\Organisms\\InvoiceForm\\InvoiceForm.tsx' => Set(0) {}
}
Axelote debug: POST http://localhost:8080/cli/tokens [
  'select invoice_id, address_to, type, payment_term from invoices where user_id = :user_id',
  "UPDATE invoices set type = 'paid' where invoice_id = :invoice_id",
  'select * from invoices where invoice_id = :invoice_id',
  'DELETE FROM invoices WHERE invoice_id = :invoice_id',
  'select * from items where invoice_id = :invoice_id',
  'where invoice_id = :invoice_id',
  'payment_term = :payment_term,',
  'invoice_date = :invoice_date,',
  'address_from = :address_from,',
  'payment_term = :payment_term',
  'invoice_date = :invoice_date',
  'address_from = :address_from',
  'description = :description,',
  'description = :description',
  'address_to = :address_to,',
  'address_to = :address_to',
  'where item_id = :item_id',
  'quantity = :quantity,',
  'quantity = :quantity',
  'update invoices set',
  'update items set',
  'and type = :type',
  'price = :price,',
  'price = :price',
  'type = :type,',
  'name = :name,',
  'type = :type',
  'name = :name'
]
`

**Comment by axelotecom** [comment] 2023-03-20 20:22
I could not reproducte this issue 

` (async () => {

    const axelote = new Axelote({
      url: "http://localhost:8074"
    });

    const repository: AxeloteRepository = new AxeloteRepository();

    repository.set('updateInvoiceItems', (params: Record<string, any>) => {

      const qb: AxeloteQueryBuilder = AxeloteQueryBuilder.query('@sql update items set');

      for (const [index, [key, _value]] of Object.entries(Object.entries(params))) {

        if(Number(index) == Object.entries(params).length - 1){

          switch (key) {
            case 'name': qb.append('@sql name = :name '); break;
            case 'price': qb.append('@sql price = :price '); break;
            case 'quantity': qb.append('@sql quantity = :quantity '); break;
          }

        }else{

          switch (key) {
            case 'name': qb.append('@sql name = :name, '); break;
            case 'price': qb.append('@sql price = :price, '); break;
            case 'quantity': qb.append('@sql quantity = :quantity, '); break;
          }

        }

      }

      qb.append('@sql where item_id = :item_id');

      return qb.build();
    });

    const itemId = 12;

    const item = {
      name: 'FV123',
      price: '100',
      quantity: '5'
    }

    const invoiceItemsQuery = repository.get('updateInvoiceItems', item);
    await axelote.void(invoiceItemsQuery, {
      ...item,
      ...{item_id: itemId}
    });
    
  })();
`

With code above. There has to be another factor. Please try with CLI 0.1.8-alpha

**Comment by GrabowskiKamil112** [comment] 2023-03-22 19:44
![image](https://user-images.githubusercontent.com/84017437/227017928-1296a306-5e33-478f-8b12-0b146cca5c19.png)

After I resigned of dynamic queryBuilder and used regular sql update everything works correctly.
I am still having trouble finding cause of the issue in the previous solution

**Comment by axelotecom** [comment] 2023-03-23 19:36
Still could not reproduce, closing

**Closed by axelotecom** 2023-03-23 19:36 UTC
Labels: bug, invalid
